import type { Metadata } from "next";
import QueryProvider from "@/app/QueryProvider";
import "./globals.css";

export const metadata: Metadata = {
    title: "오늘의 뉴스",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
